### ISSUE TITLE
force dark mode for web contents & translation in right click menu

### ISSUE THREAD

**Issue by testermania** [zen-browser/www#107]
Would you consider adding these?

force dark mode for web contents. hsl based inversion it works well.

![pic](https://github.com/user-attachments/assets/1515f0c3-7da8-46d4-9707-f10e0537072e)

& translation in right click menu

& add option to turn off translation suggestions for all sites

**Comment by n7itro** [comment]
This is not related to the Zen website. Add this issue to zen-browser/desktop instead

**Comment by testermania** [comment]
sorry delete pls
