### ISSUE TITLE
Add a list of shortcuts and general information as to how to use the browser under the "getting started" dropdown.

### ISSUE THREAD

**Issue by SomeDudeBrosky** [zen-browser/www#109]
Currently, there is a lack of end user documentation and this would be a good start.

**Comment by ktz-dev** [comment]
The documentation is under the "Useful Links" drop down but I agree, it does make sense to put it under "Getting started". Currently under "Getting started" there is a large button that says "Zen Browser" which just redirects back to the home page. This should button should instead link to a "start guide" or https://docs.zen-browser.app/guides/

<img width="654" alt="Screenshot 2024-08-26 at 11 51 11 PM" src="https://github.com/user-attachments/assets/7f0478b2-774e-4fb2-8b27-fe8d0660aaea"> <br>

It could also make sense to put some kind of guide on [the welcome page](https://www.zen-browser.app/welcome) as it is pretty empty right now and is the first thing users see after install. 

<br><img width="1343" alt="Screenshot 2024-08-26 at 11 55 20 PM" src="https://github.com/user-attachments/assets/7d6f8591-2813-457a-aa3a-15b1d916d7ba">

**Comment by SomeDudeBrosky** [comment]
I knew this page existed. However, this is more debug information and not necessarily end-user documentation. Information and guides pertaining as to how to use the marketed features and UI currently do not exist outside of reddit posts.

**Comment by ktz-dev** [comment]
I suggest that we deploy a https://nextra.site/ file-based router on the https://zen-browser.com/user-guides path or something so that end-user docs are separate from technical/developer docs. Each document will be a .mdx so we have the option of escaping the vanilla markdown for cool animations and interactive elements. It's Next.js, TypeScript and TailwindCSS. GraphQL uses it for their docs. 

<img width="1220" alt="Screenshot 2024-08-28 at 3 51 23 PM" src="https://github.com/user-attachments/assets/2f672c56-551b-4112-bc92-6817c47a12e3">

**Comment by ktz-dev** [comment]
Here is an example menu structure:

# Documentation Menu

## 1. Introduction
- Overview
- Key Features
- Getting Started
- System Requirements

## 2. Installation & Setup
- Downloading the Browser
- Installation Guide
- Initial Setup and Configuration
- Importing Data (Bookmarks, Settings, etc.)

## 3. User Interface
- Main Window Overview
- Navigation Bar
- Menu and Toolbars
- Customizing the Interface

## 4. Workspaces
- Creating and Managing Workspaces
- Switching Between Workspaces
- Workspace Settings and Customization
- Syncing Workspaces Across Devices

## 5. Split View
- Enabling Split View
- Configuring Split Layouts
- Managing Split View Tabs
- Tips for Effective Use

## 6. Sidebars
- Accessing and Using Sidebars
- Customizing Sidebar Content
- Pinning and Unpinning Sidebars
- Sidebar Shortcuts and Navigation

## 7. Flexible Tab Layouts
- Customizing Tab Layouts
- Creating Tab Groups
- Managing and Organizing Tabs
- Using Tab Layouts with Workspaces

## 8. Personalization
- Theme and Appearance Settings
- Customizing Toolbar and Menus
- Setting Up Keyboard Shortcuts
- Extensions and Add-ons
- Importing/Exporting Personal Settings

## 9. Privacy & Security
- Privacy Settings Overview
- Managing Cookies and Tracking
- Security Features and Tools
- Safe Browsing Tips
- Clearing Browsing Data

## 10. Performance & Troubleshooting
- Performance Tips and Optimizations
- Common Issues and Solutions
- How to Report a Bug
- Support and Community Resources

## 11. Advanced Features
- Developer Tools
- Command Line Options
- Experimental Features
- Custom Scripts and Automation

## 12. FAQs & Support
- Frequently Asked Questions
- Contacting Support
- Community Forums
- Documentation Feedback

## 13. Release Notes
- Latest Updates and Changes
- Version History
- Upcoming Features

## 14. Legal & Licensing
- License Information
- Privacy Policy
- Terms of Service

**Comment by ktz-dev** [comment]
It works by reading the /pages directory so if we do this, it should probably be its own repo since we are using the /app directory and it should be deployed separately on another third-level domain like the docs are. Maybe guides.zen-browser.com or something.

<img width="830" alt="Screenshot 2024-08-28 at 5 33 20 PM" src="https://github.com/user-attachments/assets/40fc6a1f-2a60-40d8-b469-210866c28b45">

**Comment by ktz-dev** [comment]
I've got the basic skeleton setup I can transfer ownership to zen-browser if they want to build on top of my skeleton or they can start their own. Check it out. [GitHub](https://github.com/ktz-dev/zen-browser-guides) | [Live](https://zen-browser-guides.vercel.app/). 

I'll continue building on top of it until its at a usable state. Right now everything except the welcome page is just a placeholder.

**Comment by mauro-balades** [comment]
https://docs.zen-browser.app is what you are looking for? If not, please feel free to reopen the issue
