### ISSUE TITLE
Unable to install themes from website

### ISSUE THREAD

**Issue by Rasmus-Bertell** [zen-browser/www#118]
Browsing the themes works fine but actually clicking the install button does nothing.
I get no console errors nor internet traffic but the button becomes disabled.

![image](https://github.com/user-attachments/assets/44fc6e6d-9692-49e1-9c22-d9d289e86d4e)

**Comment by Rasmus-Bertell** [comment]
Looked at the event attached to the button and interestingly not even the `console.info` line is printed to the console.

```JavaScript
function(event) {
  const button = event.target;
  button.disabled = true;
  const themeId = button.getAttribute("zen-theme-id");
  console.info("ZTM: Installing theme with id: ", themeId);

  const theme = await this.getThemeInfo(themeId);
  if (!theme) {
    console.error("ZTM: Error fetching theme info");
    return;
  }
  this.addTheme(theme);
}
```

**Comment by danm36** [comment]
Install button worked for me on browser 1.0.0-a.29 but no longer works on 1.0.0-a.30. Then again, I also wasn't getting the Vercel 403 issues either when I was on 1.0.0-a.29 and that was a couple of hours ago, so it could also be site related.

**Comment by mauro-balades** [comment]
The website is currently under a DDoS attack, please hold on until I fix it
