### ISSUE TITLE
Unhandled Runtime Error: dynamic = "error" with searchParams.toJSON in Next.js Route

### ISSUE THREAD

**Issue by zahyaah** [zen-browser/www#127]
I encountered an unhandled runtime error when running the application in development mode. 

**Please refer to the following screenshot:**
<img width="1440" alt="Screenshot 2024-08-28 at 7 52 53 PM" src="https://github.com/user-attachments/assets/f75db0bd-3d29-472d-90b2-7814f6d090bf">

**Comment by meetpateltech** [comment]
check this

https://github.com/zen-browser/www/issues/125#issuecomment-2314374209

**Comment by zahyaah** [comment]
thanks @meetpateltech
