### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN

### ISSUE THREAD

**Issue by noxan** [zen-browser/www#128]
Can't open the website due to a bad certificate

<img width="1154" alt="Screenshot 2024-08-29 at 3 01 22 PM" src="https://github.com/user-attachments/assets/bcfa1e61-7dce-4e47-83a7-d869ab5d727f">

**Comment by ktz-dev** [comment]
Does it work now? They did a migration yesterday and for a short period of time the site was live but without an SSL certificate.

**Comment by mauro-balades** [comment]
Yeah, I did a migration, it should be fixed now
