### ISSUE TITLE
[Documentation]: How to apply themes

### ISSUE THREAD

**Issue by scientiac** [zen-browser/www#14]
Is there an easy way to apply the themes or should the themes be manually edited on user chrome?

Also, in the theme-store repo, you've written "Sumbit a Theme" as the issue template.

**Comment by n7itro** [comment]
A system for applying a theme from the website is currently being worked on, as it is not intended to manually apply it.
The issue template is used for submitting themes, but you can still open a blank issue without any template on the repository.

**Comment by scientiac** [comment]
I mean the typo, "Sumbit"

**Comment by mauro-balades** [comment]
Since version 22, themes will now work directly from the website. If you want to submit one, please checkout https://github.com/zen-browser/theme-store?tab=readme-ov-file#submitting-a-theme
