### ISSUE TITLE
Follow system color scheme preference

### ISSUE THREAD

**Issue by bragefuglseth** [zen-browser/www#140]
The website is currently dark by default, with a toggle to switch between light/dark mode. Maybe it should be made to follow the system by default, using the [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media feature?

**Comment by ktz-dev** [comment]
Its tricky getting it to work nicely with TailwindCSS. The CSS library we are using. I sent the PR with the fix.
