### ISSUE TITLE
Application error. Cannot open the website

### ISSUE THREAD

**Issue by rycerzes** [zen-browser/www#155]
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 2727957145
![image](https://github.com/user-attachments/assets/12e76251-6773-4ca1-aaac-21c8e9d2199d)

**Comment by abenezerw** [comment]
Same

**Comment by VamsiPunnaReddy** [comment]
Check my PR i already submitted the solution

**Comment by mauro-balades** [comment]
Should be working now
