### ISSUE TITLE
Locale changes breaking buttons on homepage

### ISSUE THREAD

**Issue by btylerh7** [zen-browser/www#159]
I see that the site has been updated to use the user's locale (ex. `/en`) on the homepages, but the theme store and download buttons in the features component for the homepage is still linking to `/download` and `/themes`. This is making the links break. However, if i try to go to `/en/themes` manually, the page loads correctly. I am not sure what the best way to incorporate the locale string into the button click handlers would be. 

Examples of where this is happening: 
- https://github.com/zen-browser/www/blob/0bdd1eaa28e19a0f9f72692c0bdca2b6647c51b3/src/components/features.tsx#L92
- https://github.com/zen-browser/www/blob/0bdd1eaa28e19a0f9f72692c0bdca2b6647c51b3/src/components/features.tsx#L100

**Comment by btylerh7** [comment]
Just noticed that this also is causing issues when going to the page for an individual page, ex https://zen-browser.app/themes/83a641f7-eca9-4c0f-91af-45627bef0539

**Comment by mauro-balades** [comment]
This is fixed
