### ISSUE TITLE
Release Notes pages should have Next and Previous links

### ISSUE THREAD

**Issue by burnout426** [zen-browser/www#16]
On <https://www.zen-browser.app/release-notes/1.0.0-a.17> for example, it would be nice to have a link you can click on to goto the previous release notes and a link to goto the next release notes.

As is now, you have to keep going back to <https://www.zen-browser.app/release-notes> to get to the next or previous one or open all the links you want on the <https://www.zen-browser.app/release-notes> page in a new tab and then switch tabs.

**Comment by mauro-balades** [comment]
very true

**Comment by burnout426** [comment]
Nice! So much easier to navigate the release notes now.
