### ISSUE TITLE
About Us Page is empty

### ISSUE THREAD

**Issue by broadcoder** [zen-browser/www#161]
Hey, I found out about this awesome sounding and promising browser project.

We have though times. The trust into the internet is melting. Tracking and Ads (that even can be malicious) is a rising problem along with security in general. This Browser is for sure a light house from what it promises on it's website, not only the features but the fact it's based on latest firefox cought my attention. I really see me using it, when it's a stable product.

However, the times where I install things from the iternet blindly are over. Especially after I saw an issue in the desktop repo that it even detects some trojans. Even tho those very likely be false positives, I won't take a risk for now. So I was interested who is behind this project, how it works in regards on keeping firefox up to date in the same pace firefox is, does it happen automatically by firefox or does the project needs to do this and also create a new release? What if time is short and important security fixes are available in FF but not in Zen? 

So I tried to get more information and discovered that the About Us page is empty: https://zen-browser.app/about
Any plans on giving more transparence who is behind this project and what the roadmap is? When it will enter beta stage, when it will have a first stable version? What are the requirements, what are the goals?

Thank you so much in advance

**Comment by broadcoder** [comment]
Seems like the about page is working again, at the time when I posted it was empty. 

Would still like to get some of the questions answered, if someone finds the time :)
Could be worth putting answers to those kind of questions on the website as well.

But the main issue, that about page was blank, seems to be resolved so feel free the close it, if no further action is taken into account 👍

**Comment by NOCanoa** [comment]
hi, 
1) Assuming u are talking about Windows, Cheff has bean in real pain whit apple and Microsoft, not responding, but now Microsoft finally responded and it should all be working from their side, so in the next updates MS license should be signed correctly and  that should fix all the warnings.

2)Updates, Upstream updates always have a small delay in FF forks, we always checking FF official releases so if something new pops up we can respond/update in the fasted ways possible, (minimum delay is 4h corresponding to the build time, + any manual fixing time).

Did i get everything?
