### ISSUE TITLE
Dark mode to Light mode requires two clicks

### ISSUE THREAD

**Issue by grainme** [zen-browser/www#170]
When attempting to toggle between dark mode and light mode, the switch requires two clicks.

Expected behavior:
  - Theme should switch between dark & light mode with a single click.

![Screenshot 2024-09-12 at 10 01 12](https://github.com/user-attachments/assets/67a5ae60-38a4-4f0f-ba44-a0022a994cd6)

**Comment by Kroszborg** [comment]
Yes i noticed that too. Dark to light takes two clicks but light to dark takes single click.

**Comment by grainme** [comment]
I just saw the fix you pushed, looks fine to me :)

**Comment by Kroszborg** [comment]
Yea I didn't notice that before pushing my fix tho it's my first ever contribution to an open source project, I'm feeling great rn.

**Comment by grainme** [comment]
Congrats mate, hopefully it get merged.

**Comment by Kroszborg** [comment]
Thanks man

**Comment by ktz-dev** [comment]
#173 is merged. This can be closed.
