### ISSUE TITLE
Discord Link Broken?

### ISSUE THREAD

**Issue by crnobog69** [zen-browser/www#175]
I wanted to join Disord server but the link to Discord server on the Zen website doesn't work.

![image](https://github.com/user-attachments/assets/b81fdead-80d5-4926-8468-c8c358d88e30)

**Comment by Kroszborg** [comment]
yes, noticed it right now. Here is the correct link for now- https://discord.gg/mauro-s-little-sweatshop-1088172780480114748

**Comment by crnobog69** [comment]
Thank you!

**Comment by Kroszborg** [comment]
No problem man
