### ISSUE TITLE
It's not possible to navigate from the home page with javascript disabled

### ISSUE THREAD

**Issue by AlfonsoML** [zen-browser/www#188]
All the "links" are buttons with javascript that perform the navigation actions, and if javascript is disabled for any number of reasons then none of those buttons work.

![imagen](https://github.com/user-attachments/assets/40f9e627-886c-48af-9fda-fd816e15c260)

**Comment by ZhenyaGoroh** [comment]
What is the reason to use Button instead of Link tag?
