### ISSUE TITLE
Streamlined misspelled

### ISSUE THREAD

**Issue by leanghok120** [zen-browser/www#19]
![image](https://github.com/user-attachments/assets/993eb445-fbae-47f5-a2a9-508c5a36f13a)

Just visited the zen browser landing page and found this typo

**Comment by leanghok120** [comment]
Okay so after forking the repo and running it on my local machine. There actually is no space but in the site there is

![image](https://github.com/user-attachments/assets/dfe5f454-8e70-4639-abe3-ec65cf17deee)

**Comment by mauro-balades** [comment]
👍🏽
