### ISSUE TITLE
Remove trackers

### ISSUE THREAD

**Issue by PinguDEV-original** [zen-browser/www#198]
Hey there! You have some trackers on your webpage. This is maybe a bit bad as you claim not to track and are pro-privacy. Maybe remove the trackers then?

**Comment by mauro-balades** [comment]
Do you mean? https://plausible.io/zen-browser.app

**Comment by n7itro** [comment]
Trackers do not inherently worsen personal privacy. The data is anonymous and is solely used for analytics
