### ISSUE TITLE
Radio buttons for selecting the OS during download should be circular 

### ISSUE THREAD

**Issue by WeetHet** [zen-browser/www#20]
It's a well known convention ([if somewhat dying](https://tonsky.me/blog/checkbox)), that a rectangular box means that there's a multiple selection (a checkbox) and a circular button is a choose one out of the following. The OS selection (and maybe some other things) don't seem to follow this convention. It doesn't really ruin the design, so just for the matter of consistency, if you could change the shape, it would be nice. The other option is to just remove the checkboxes, as the outline does the job fine

![Screenshot_20240820-212729~2](https://github.com/user-attachments/assets/e22e9253-3154-4bda-bce2-0fad64a505cc)

**Comment by mauro-balades** [comment]
I like them this way, they aren't radios, they are checkboxes :]

**Comment by WeetHet** [comment]
> I like them this way, they aren't radios, they are checkboxes :]

I can't choose two of them at the same time, that does make them radios

> A radio button or option button is a graphical control element that allows the user to choose only one of a predefined set of mutually exclusive options.

From: [Wikipedia](https://en.m.wikipedia.org/wiki/Radio_button)
