### ISSUE TITLE
you can skip selecting a OS version.

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/www#210]
if you try to download the installer but don't select an OS version and you are on a non-supported device it takes you to a page that says continue and if you press that it will give a download option that does not work.

I only found this out because my friend tried to download zen as a joke on a school chromebook.

**Comment by NOCanoa** [comment]
Dont kwite understand what url did u start and what url was the bug?

**Comment by ZhenyaGoroh** [comment]
How to reproduce it?

**Comment by Vigneshk5** [comment]
He is talking about trying to download the installer on an unsupported OS (ChromeOS). If you don't select an OS version, you're given a download option that doesn't work.

https://github.com/user-attachments/assets/55e5018b-6ce3-4555-8dd2-d4389d621a62

**Comment by ZhenyaGoroh** [comment]
> He is talking about trying to download the installer on an unsupported OS (ChromeOS). If you don't select an OS version, you're given a download option that doesn't work. Option: Disable the 'Continue' button if unsupported OS is selected.
> Screen.Recording.2024-10-05.at.5.53.43.PM.mov
> 
> fixed(in case of unsupported OS)
> Screen.Recording.2024-10-05.at.6.22.11.PM.mov
> 
> Can I submit PR?

Open a pr. Also as I see, u just disabled Continue button, but mb u add some text that informs that user's os is not supported

**Comment by Vigneshk5** [comment]
How about this?

<img width="1437" alt="Screenshot 2024-10-05 at 9 37 54 PM" src="https://github.com/user-attachments/assets/c3cd0f38-c2a6-4657-8ed4-b8503213758e">
