### ISSUE TITLE
OS selection interface blink

### ISSUE THREAD

**Issue by ZhenyaGoroh** [zen-browser/www#216]
@Vigneshk5 You have fixed bug with os selection for os's that are not supported. But now when I open this page, I see this message that my os is not supported for a second and then it disappears. Could u fix it somehow?

![image](https://github.com/user-attachments/assets/34707d91-d435-4d65-8e65-675c12ff2e09)

**Comment by Vigneshk5** [comment]
I think it's because of the delay in		```
if (typeof window !== "undefined") {
			userAgent = window.navigator.userAgent;
		}
```

**Comment by ZhenyaGoroh** [comment]
Maybe just call setSelectedPlatform with 'undefined' or something like this and then check this value? So this message will be shown only if platform really not supported

**Comment by Vigneshk5** [comment]
That introduces a type error. Instead, we can use a state to track if selectedPlatform has been assigned.

https://github.com/user-attachments/assets/e9dbdcfd-f14b-4b49-bb9f-e858a23b8965
