### ISSUE TITLE
"Stable" automatic installer script reference when downloading Twilight

### ISSUE THREAD

**Issue by LeMoonStar** [zen-browser/www#219]
The website informs users that they can use a script to automatically install the Zen AppImage when choosing AppImage.
This script is currently only avaliable for "stable" Zen alpha and **does not support Zen Twilight**.

When downloading Zen Twilight, the same message is shown, possibly missleading users to install "stable" Zen alpha instead of twilight.

The relevant line of code can be found here: https://github.com/zen-browser/www/blob/3f5b6dec0418a137edf92faaa091e375342af562/src/components/download.tsx#L247-L250

~~Either the install script should support Zen Twilight OR a Zen Twilight specific install script has to be made OR the website shouldn't show this hint.~~
***EDIT: The Install script now supports Zen Twilight! Twilight can be installed using `bash <(curl https://updates.zen-browser.app/appimage.sh) twilight`!***

~~EDIT: The referenced install script can be found [here](https://github.com/zen-browser/updates-server/blob/a256f17b854e9591e5bf2cd46e7ac1b8026e7837/appimage.sh). (Old version)~~

**Comment by LeMoonStar** [comment]
The installer script can now install/manage Twilight installs by simply adding `twilight` as the first parameter. See https://github.com/zen-browser/updates-server/pull/8

**Comment by LeMoonStar** [comment]
This means, for "stable" Zen, the command `bash <(curl https://updates.zen-browser.app/appimage.sh)` can be used, as before
and for Zen Twilight, the command `bash <(curl https://updates.zen-browser.app/appimage.sh) twilight` can be used starting now.

**Comment by NOCanoa** [comment]
Nice!
