### ISSUE TITLE
Download offers Flatpak when selecting optimized, even though there is no optimized flatpak

### ISSUE THREAD

**Issue by LeMoonStar** [zen-browser/www#220]
When downloading (stable, non-twilight) Zen, selecting Linux and Optimized, flatpak is offered, even though there is no optimized version of the Flatpak - the downloaded `.flatpakref` file is the exact same as the one provided when selecting generic.

Offering the flatpak after selecting optimized may cause users to be mislead to install the generic version instead.
While removing the flatpak option is possible, it might be worth noting that flatpak is an installation option - I thus propose to instead still offer it, but clearly mark it as unoptimized.

**Comment by ZhenyaGoroh** [comment]
@NOCanoa Is it really like this? I mean is it real that flatpak has no optimized version? Even if so, it's not correct to delete flatpak from optimized, cuz user couldn't find it. I can add some info text to inform users.

**Comment by NOCanoa** [comment]
@ZhenyaGoroh ye there is no optimized version of flatpak,

**Comment by LeMoonStar** [comment]
> [...] Even if so, it's not correct to delete flatpak from optimized, cuz user couldn't find it. I can add some info text to inform users.

I fully agree it should still be offered, just with an added warning that it is NOT the optimized version.
Not offering Flatpak could cause users to not install Zen, as AppImages and portable versions are way less convenient.

**Comment by ZhenyaGoroh** [comment]
https://github.com/zen-browser/www/pull/224

I tried to fix it in this pr, check the text pls

**Comment by LeMoonStar** [comment]
I don't thing this is truly fixed. The Added message does not really make it clear to the user.
See https://github.com/zen-browser/www/pull/224#issuecomment-2402998885 for more details.

**Comment by ZhenyaGoroh** [comment]
> I don't thing this is truly fixed. The Added message does not really make it clear to the user. See [#224 (comment)](https://github.com/zen-browser/www/pull/224#issuecomment-2402998885) for more details.

I have an idea, I'll try to implement in now
