### ISSUE TITLE
Temporary containers automatic container creation is not working. 

### ISSUE THREAD

**Issue by somerandom2** [zen-browser/www#240]
Hello,

You can test by yourself. Install temporary containers, go to settings and enable automatic mode. It should create container each time you open a tab, but it is not doing it.

**Comment by sjclayton** [comment]
Feature requests (discussions) and bugs (issues) for the browser should be filed over here --> https://github.com/zen-browser/desktop

This repo is for the Zen website.

**Comment by NOCanoa** [comment]
⬆️
