### ISSUE TITLE
Customizable keyboard shortcut request: next tab, previous tab

### ISSUE THREAD

**Issue by somerandom2** [zen-browser/www#241]
I want to edit default next tab (CTRL+TAB) and previous tab (CTRL+SHIFT+TAB) shortcuts. Changing it will be nice.

**Comment by sjclayton** [comment]
Feature requests (discussions) and bugs (issues) for the browser should be filed over here --> https://github.com/zen-browser/desktop

This repo is for the Zen website.

**Comment by NOCanoa** [comment]
⬆️
