### ISSUE TITLE
Using consisted naming convension

### ISSUE THREAD

**Issue by somerandom2** [zen-browser/www#242]
In the shortcut menu there is the Toggle Sidebar's Width shortcut, but this shortcut increases the vertical tab bar. The actual open Zen Sidebar shortcut is the Toggle Web Panel shortcut. This causes some confusion. The fix will be nice.

**Comment by sjclayton** [comment]
Feature requests (discussions) and bugs (issues) for the browser should be filed over here --> https://github.com/zen-browser/desktop

This repo is for the Zen website. This issue should be closed.

**Comment by NOCanoa** [comment]
True naming is a bit messed up
