### ISSUE TITLE
Border around the browser

### ISSUE THREAD

**Issue by ArchieA** [zen-browser/www#246]
First, thank you for such a fantastic idea for a minimalist web browser. I really love it!

My issue is negligible but Zen could be more aesthetically pleasing on my desktop if there is any way I can make the border around the browser or even completely remove it.

Thank you for your attention, and best wishes.

**Comment by NOCanoa** [comment]
this is the rong repo lol, but u can try this theme https://zen-browser.app/themes/680424a8-a818-406b-98c5-7726214e2a9f
