### ISSUE TITLE
Author name != author's Github slug

### ISSUE THREAD

**Issue by shanto** [zen-browser/www#255]
https://github.com/zen-browser/www/blob/aa9bb54d219148aa62cfdc2d15b9047ee18594dc/src/lib/mods.ts#L198

I request making author name and author's github slug be kept in separate fields in the theme meta structure. E.g.

```
{
	"id": "39907934-59e9-4e42-89f0-a254d3c5e280",
	"name": "Sidebery",
	"description": "Tweaks to support Sidebery as an alternative to Zen's native tabs and workspace implementation.",
	"homepage": "https://github.com/shanto/sidebery",
	"style": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/39907934-59e9-4e42-89f0-a254d3c5e280/chrome.css",
	"readme": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/39907934-59e9-4e42-89f0-a254d3c5e280/readme.md",
	"image": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/39907934-59e9-4e42-89f0-a254d3c5e280/image.png",
	"author": {
		"name": "Shaan",
		"github": "shanto"
	},
	"version": "1.0.0",
	"preferences": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/39907934-59e9-4e42-89f0-a254d3c5e280/preferences.json",
}

```

**Comment by Mailootje** [comment]
> https://github.com/zen-browser/www/blob/aa9bb54d219148aa62cfdc2d15b9047ee18594dc/src/lib/mods.ts#L198
> 
> I request making author name and author's github slug be kept in separate fields in the theme meta structure. E.g.
> 
> ```
> {
> 	"id": "39907934-59e9-4e42-89f0-a254d3c5e280",
> 	"name": "Sidebery",
> 	"description": "Tweaks to support Sidebery as an alternative to Zen's native tabs and workspace implementation.",
> 	"homepage": "https://github.com/shanto/sidebery",
> 	"style": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/39907934-59e9-4e42-89f0-a254d3c5e280/chrome.css",
> 	"readme": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/39907934-59e9-4e42-89f0-a254d3c5e280/readme.md",
> 	"image": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/39907934-59e9-4e42-89f0-a254d3c5e280/image.png",
> 	"author": {
> 		"name": "Shaan",
> 		"github": "shanto"
> 	},
> 	"version": "1.0.0",
> 	"preferences": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/39907934-59e9-4e42-89f0-a254d3c5e280/preferences.json",
> }
> ```

Does it work again? There was a issue

**Comment by shanto** [comment]
> Does it work again? There was a issue

@Mailootje It doesn't work. According to above the code link, theme repo and live site (as built), Github link is derived from the single `author` field. I propose that it becomes a separate JSON object having two or more fields such as `author.name`, `author.github`, `author.xyz`.

**Comment by mauro-balades** [comment]
Auther's name is gotten based on the PR author, meaning that the name IS their github

**Comment by shanto** [comment]
> Auther's name is gotten based on the PR author, meaning that the name IS their github

@mauro-balades we are taking author's Github slug from the PR, which is not always same as name.

**Comment by mauro-balades** [comment]
Author isn't supposed to be the name, but the GitHub account that posted the theme
