### ISSUE TITLE
Link to instructions to Run Locally, doesnt explain how to run locally

### ISSUE THREAD

**Issue by Richard-Woessner** [zen-browser/www#258]
On the browser repo the readme states

Run Locally
In order to download and run zen locally, please follow [these instructions](https://docs.zen-browser.app/contribute/desktop).

But the web page does not actually explain how to install, only how to branch

**Comment by Mailootje** [comment]
Is this for the website or desktop application?

**Comment by NOCanoa** [comment]
https://github.com/zen-browser/docs/pull/64
