### ISSUE TITLE
feat(i18n): introduce

### ISSUE THREAD

**Issue by AugustinMauroy** [zen-browser/www#27]
- use [next-int](https://next-intl-docs.vercel.app)
  - Allow to create a middleware
  - Message on server and client component

**Comment by AugustinMauroy** [comment]
cc @mauro-balades

**Comment by mauro-balades** [comment]
Yes yes, I'm thinking on how I could do it, thanks!

**Comment by AugustinMauroy** [comment]
If you want i can do it

**Comment by mauro-balades** [comment]
l18n will not be added (after previus attempts) because it's just not possible with static pages and previous link compatibility
