### ISSUE TITLE
Search function of mods store site produces error when on last page.

### ISSUE THREAD

**Issue by dev-adal** [zen-browser/www#271]
Hello!
Today I've been exploring the zen mods and encountered the following error:
When looking at mods on the last page of the available mods (currently page 6) (https://zen-browser.app/mods?page=6) and entering a unknown character into the search bar (or I guess a character, which isn't used in any mod), my screen changes to white and displays the following text in the middle of the page: 
![image](https://github.com/user-attachments/assets/376af66e-28e8-4cd1-97c0-d4f8168e2fea)

When looking into the console, the following can be seen:
![image](https://github.com/user-attachments/assets/2d08a89e-014b-42d5-af6a-31ab4cd121ac)

This behaviour can be seen on atleast these Browsers: Google Chrome, Edge and Zen.

I hope this is helpful. 

Kind Regards.
adal

**Comment by TheRealMG** [comment]
Added some logic in my PR #269 to hopefully fix this issue.

**Comment by Heinrich-XIAO** [comment]
Should this be closed?
