### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN on zen-browser.app

### ISSUE THREAD

**Issue by tagptroll1** [zen-browser/www#289]
I can't say this is a zen browser bug in itself, as its reproduceable on edge. But should be shed some light on.

I can't download the nagging update from zen-browser.app because the cert is bad.
On edge its saying net::ERR_CERT_COMMON_NAME_INVALID
Zen is saying SSL_ERROR_BAD_CERT_DOMAIN
```
Websites prove their identity via certificates. Zen Browser does not trust this site because it uses a certificate that is not valid for zen-browser.app. The certificate is only valid for the following names: dns-error.telenor.net, *.telenor.net
```

![image](https://github.com/user-attachments/assets/fcee60d9-7ecc-47ce-ad7a-b438581769bf)

**Comment by NOCanoa** [comment]
Continue https://github.com/zen-browser/www/issues/295
