### ISSUE TITLE
Zen Mods Page removes order filter after "Go Back" is pressed while viewing individual mod

### ISSUE THREAD

**Issue by dev-adal** [zen-browser/www#292]
Hello Everyone!

Steps to reproduce:

- go to https://zen-browser.app/mods
- order mods by "Created Date"
- set order of mods to descending (arrow down icon next to created date filter)
- click on any mod
- click on "Go Back" while viewing the mod

Now the order filter (descending (desc)) has been reset to ascending.

Screenshot before:
![image](https://github.com/user-attachments/assets/0308ab05-39e8-4e15-b096-7e50a3445d19)

Screenshot after:
![image](https://github.com/user-attachments/assets/1cd04b02-9cd8-4843-ba51-7e88de6c5cac)

Tested on the following browsers: Zen, Chrome, Edge

Kind Regards.
adal

**Comment by r0ld3x** [comment]
@NOCanoa it doesnt fix that issue

url is `/mods?order=desc`  and we pressed back the url becoms `/mods` but the page data doesn't changes. it shows data of `order=desc `

**Comment by NOCanoa** [comment]
👌 gimi 5h. When back at pc
