### ISSUE TITLE
Unable to connect to "https://zen-browser.app/" domain

### ISSUE THREAD

**Issue by sarisman84** [zen-browser/www#294]
I am unable to connect to the website due to a time out error:

![image](https://github.com/user-attachments/assets/4745cd2c-7095-4647-9b02-b9b25d310ec5)

I have tried several different browsers (edge, firefox, chrome) and those don't work either.
This causes several issues to occur onto the zen browser itself, such as being unable to access the mods section of the website as well as the web browser being unable to automatically update itself.

![image](https://github.com/user-attachments/assets/2e842e3b-0279-4e42-8e8a-9aab2c5a4007)

Furthermore, the download button leads to the same time out error.

I do not have any internet issues on my end as every other website has been working fine for me.

Really not sure what to do here.

**Comment by NOCanoa** [comment]
What is ur DNS provider?

**Comment by sarisman84** [comment]
My DNS Provider is 8.8.8.8 (Google).

**Comment by NOCanoa** [comment]
> My DNS Provider is 8.8.8.8 (Google).

hmm is there any firewall that might be blooking it?
