### ISSUE TITLE
Proper domain?

### ISSUE THREAD

**Issue by Zoobdude** [zen-browser/www#3]
Just wondered if there are plans to buy a proper domain? Or just continue with Vercel domain?

**Comment by mauro-balades** [comment]
Im just having a hard time deciding what domain I should buy

**Comment by IAmJafeth** [comment]
welcome

**Comment by mauro-balades** [comment]
hehe, we've got one now https://www.zen-browser.app

**Comment by Zoobdude** [comment]
Good choice!

**Comment by Zoobdude** [comment]
Looks like the domain could be updated in the about section:

![image](https://github.com/user-attachments/assets/4c975f86-45c3-461e-aab6-fe26cfc6ac30)

**Comment by mauro-balades** [comment]
True, ill fix it
