### ISSUE TITLE
Website has Some Responsiveness Issue!

### ISSUE THREAD

**Issue by devishraq** [zen-browser/www#30]
My Laptop screen is 1980*1080. Browser: Google Chrome!

I saw all these responsiveness-related issues here!

Padding Needed:-
![image](https://github.com/user-attachments/assets/7e78de73-9ae4-43fc-8522-6511eb70cc9d)
![image](https://github.com/user-attachments/assets/896840a3-c358-4d50-b005-49442c338519)
![image](https://github.com/user-attachments/assets/9e1a3353-3ba5-4632-96ad-d6910190f5a1)

This Flexbox needs to be fixed:-
![image](https://github.com/user-attachments/assets/c965f487-16c5-45c1-b033-72ad19eb0530)

All of them are not a major issue; a simple responsiveness trick must be applied..... Re-configuring tailwindcss class would make this okay!

**Comment by devishraq** [comment]
I think I would be able to solve this issue...Any One please assign me this?

**Comment by n7itro** [comment]
> I think I would be able to solve this issue...Any One please assign me this?

You can fork the repository and create a pull request for your changes

**Comment by mauro-balades** [comment]
As nitro said, create a fork and send a pr, thanks!
