### ISSUE TITLE
The subscribe button is above the like button 

### ISSUE THREAD

**Issue by michaelrodriguess** [zen-browser/www#314]
look the prints below:

![image](https://github.com/user-attachments/assets/bfdb473b-f138-4791-988b-10ebe473a3ea)

![image](https://github.com/user-attachments/assets/bd454d5b-2ca8-4f4a-8d95-9b17c83c5ce8)

**Comment by cheng-dai** [comment]
This repo is for the official website of the browser, 
[open an issue here](https://github.com/zen-browser/desktop)

**Comment by NOCanoa** [comment]
> This repo is for the official website of the browser, [open an issue here](https://github.com/zen-browser/desktop)

⬆️

**Comment by NOCanoa** [comment]
also that looks more like a YT bug 🤷‍♂️
