### ISSUE TITLE
Certificate issue in linux

### ISSUE THREAD

**Issue by andynu** [zen-browser/www#32]
Hi. I'm running a bog standard Ubuntu 24.04.

https://zen-browser.app/welcome/

Kind-of hilariously your website does not display either in firefox or the zen browser itself on my system. It shows a Secure Connection Failed. PR_CONNECT_RESET_ERROR. Something to do with my system validating your website's certificate I think.

![image](https://github.com/user-attachments/assets/3806c28a-ffca-4acb-8ab6-2c63e4a4967f)

**Comment by NOCanoa** [comment]
i am getting full ssl on the domain,
still happening?

**Comment by andynu** [comment]
Yup. Still happening.

![image](https://github.com/user-attachments/assets/2bba3b4b-36e8-4766-a3b2-f0a7cac166a9)

**Comment by andynu** [comment]
Trying to show the full cert I get:
![image](https://github.com/user-attachments/assets/24b68764-9ac6-4687-b175-242cd22ea981)

**Comment by NOCanoa** [comment]
i realy dont know

**Comment by andynu** [comment]
The site got flagged as 'phishing' by a corporate firewall.
Hopefully, false positives like this will decrease as this fork gains
popularity.
Sorry for the noise. Cheers.
