### ISSUE TITLE
Problems with the search bar with the compact mode

### ISSUE THREAD

**Issue by santigids** [zen-browser/www#337]

**Comment by BramLeisink** [comment]
As far as I know, there is no search bar on the Zen-Browser website. If you intended to report this for the browser itself, please use this link: https://github.com/zen-browser/desktop/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen .

After creating the issue there, kindly close this one and include as much detail as possible in your new report.

Have a great day!
