### ISSUE TITLE
Old icon on website page

### ISSUE THREAD

**Issue by Minus10Celcius** [zen-browser/www#346]
![image](https://github.com/user-attachments/assets/590f655f-d0ec-4a1a-8d55-ba5bed0c8ba6)

**Comment by shvhil** [comment]
That's strange. 
The release notes page (https://zen-browser.app/release-notes/) seems to have the updated logo/favicon. 

Perhaps try clearing your cache? If it still persists, try sharing the link here.

**Comment by aelaraji** [comment]
it must be the cache ... 
![2024-12-12_12-20-48_243x68](https://github.com/user-attachments/assets/b140742c-d262-432e-ab20-6cfadd0e6a6f)

**Comment by LucasM314** [comment]
It's definitely the cache, the old icon was showing up for me too and clearing Firefox's cache solved the issue.
