### ISSUE TITLE
Seems like settings windows is not resizing according to window's size!

### ISSUE THREAD

**Issue by sameercreates** [zen-browser/www#357]
Not a big one but guess its an issue..
![{A313FCC1-236C-4056-8D9A-448CA07EF092}](https://github.com/user-attachments/assets/4d322aa4-fc4c-4f39-a8e3-6ac6ff66cb85)

**Comment by NOCanoa** [comment]
wroung repo lul, this is the site repo
https://github.com/zen-browser/desktop/issues
