### ISSUE TITLE
Uninstall window message 

### ISSUE THREAD

**Issue by tpbhagwat** [zen-browser/www#36]
While uninstalling the browser from Windows Desktop, the last window shows the message below.

"Tell Mozilla why you uninstalled Zen Browser."

Not sure, why I need to inform Mozilla about the reasons for uninstalling the browser. Please check. Thanks in advance.

**Comment by Bazixv13** [comment]
this is the site repo. issues referring to the Zen browser should be reported [there](https://github.com/zen-browser/desktop/issues) :3
