### ISSUE TITLE
Confusing UI on release note dropdowns

### ISSUE THREAD

**Issue by Fireye04** [zen-browser/www#377]
This could be an intentional choice so feel free to close this issue if so, however, the [release note](https://zen-browser.app/release-notes/) dropdowns (eg:fixes, features) aren't very visibly dropdowns from a user perspective. I might be flagging my own autism here but it took me a good 30 seconds to realize that I could expand them. 

![image](https://github.com/user-attachments/assets/ec30cdfd-740c-4f73-95a3-87cdf4096ea4)

Here are a couple of potential modifications that could help improve user experience:
- Move the + icon to the left of the dropdown option to make it more visible on a larger screen
- Improve the contrast on the lines below each dropdown
- Change the + icon to an arrow
- Auto expand the dropdowns on the latest release

Feel free to take any or none of the above suggestions. I'd be happy to open a PR and make the modifications myself, I just want to do so in a way that's cool with the maintainers here :+1:

**Comment by KyleDL101** [comment]
Added some of the adjustments you've mentioned here #378

**Comment by KyleDL101** [comment]
This can probably be closed

**Comment by Fireye04** [comment]
> This can probably be closed

Oh, will do, thanks for the fixes!
