### ISSUE TITLE
Referencing a non-existing Release

### ISSUE THREAD

**Issue by Crazyroostereye1** [zen-browser/www#387]
The Website is referencing a new release (1.0.2-b.4) on the website (https://zen-browser.app/release-notes/#1.0.2-b.4) that doesn't exist. The links 404 to GitHub,

**Comment by KyleDL101** [comment]
#388 will fix, but i asked cheff and he said he was going to release the update today and things got sidetracked. the update might still release today or tomorrow (hopefully), so not sure if it's worth taking down atm just to have to put it back up. idk, up to the maintainers to decide.

**Comment by Crazyroostereye1** [comment]
Makes sense, the Version is now here, so I can close the Issue :)
