### ISSUE TITLE
Cloudflare protection prevents RSS feed to be fetched by RSS readers

### ISSUE THREAD

**Issue by axeleroy** [zen-browser/www#396]
Hello,

It seems that the website is now behind Cloudflare's DDoS protection and because of this, RSS readers can no longer fetch the RSS feed.

A simple way to reproduce the issue is to use curl[^1]:

```shell
$ curl https://zen-browser.app/feed.xml

<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe
```

[^1]: I truncated the response in order to not bloat the issue.

Copying the request as a cURL from the developer tools leads to the same result.

**Comment by NOCanoa** [comment]
add:
https://share.thatcanoa.org/ss/WindowsTerminal_B75ZKVP0kx.png

**Comment by mr-cheff** [comment]
Please user normal images instead of links

**Comment by NOCanoa** [comment]
@mr-cheff normal now?
![image](https://github.com/user-attachments/assets/da1aacc8-f9b7-42ab-ae2a-22ca656042ca)

**Comment by mr-cheff** [comment]
Weird, it works at https://openrss.org/zen-browser.app/feed.xml

**Comment by mr-cheff** [comment]
Ok, fixed
