### ISSUE TITLE
Mozilla sync

### ISSUE THREAD

**Issue by LIlaUraraka** [zen-browser/www#399]
I have been having consistent issues with the sync, random, disconnects for no discernible reason, disconnecting when I go to look at my account page, and getting locked out of my account, causing me to not be able to sign in on any device. This has been an issue for a few updates now, and is a huge problem, especially for those who use sync daily. these screenshots are a few of what I am experiencing 
![2024-12-12 14_28_31-](https://github.com/user-attachments/assets/94d04c63-86f4-42ae-be3a-1dfe8c1f079a)
![2024-12-31 00_55_33-Settings — Zen Browser](https://github.com/user-attachments/assets/73da8702-d26e-487c-98c2-7da8fcaa2751)

**Comment by KyleDL101** [comment]
@LIlaUraraka Please log this as in issue for the browser's repo here: [https://github.com/zen-browser/desktop](https://github.com/zen-browser/desktop)

This is the repo for the website itself.

**Comment by LIlaUraraka** [comment]
oh, my bad
