### ISSUE TITLE
Download page should mention what version you're downloading

### ISSUE THREAD

**Issue by burnout426** [zen-browser/www#4]
For a better experience, <https://get-zen.vercel.app/download> should mention the version and build number for the download.

**Comment by mauro-balades** [comment]
It has actually been rewritten, the new version will be released once .11 is released, thanks!

**Comment by burnout426** [comment]
I see the website has been updated, but still no mention on the download page what version you're downloading. 
I know one can goto <https://www.zen-browser.app/release-notes>, but maybe the download page can mention "Current Release: version" or something.
