### ISSUE TITLE
Download blocked by firewall

### ISSUE THREAD

**Issue by ricardobeat** [zen-browser/www#40]
Because of the fresh registration date (2024-08-06) the zen-browser.app domain is blocked. This is probably the case for anyone behind a corporate VPN or firewall. The README points to the same domain as the only source for downloading.

Allowing download via GitHub releases, or trusted mirrors, would alleviate the issue. I assume there are also plans to make it available in the App Store.

**Comment by NOCanoa** [comment]
Github releases is avaliable,
and the domain age we can only wait
