### ISSUE TITLE
typo and grammar corrections in zen browser features

### ISSUE THREAD

**Issue by zahyaah** [zen-browser/www#46]
## Issue Description
1. there's a small typo in the features content: "We are constantly tweak firefox's engine and settings..." should be corrected to **"We are constantly tweaking Firefox's engine and settings..."**  
2.  also, let’s capitalize **"Firefox"**
<img width="334" alt="Screenshot 2024-08-23 at 1 55 57 AM" src="https://github.com/user-attachments/assets/fd34c947-dce5-4235-bae1-7411098b0890">
<img width="467" alt="Screenshot 2024-08-23 at 1 54 15 AM" src="https://github.com/user-attachments/assets/7cf83872-400d-4058-9e9c-f2cb4e3ab269">

**Comment by mirza-mohibul-hasan** [comment]
Is the issue solved?

**Comment by zahyaah** [comment]
> Is the issue solved?

Yes, please [check](https://github.com/zen-browser/www/pull/48)
