### ISSUE TITLE
Optimized and Generic not specified, nor appears what it changes

### ISSUE THREAD

**Issue by SoftwareType** [zen-browser/www#5]
Hello there,

I've noticed a simple problem:
![image](https://github.com/user-attachments/assets/5b2416ee-1f8f-42c7-883d-3dd52b6f33fc)
it doesn't specify what has been changed or what is different from the other (if it uses newer technologies, etc)
The same isn't specified on the GitHub README

**Comment by mauro-balades** [comment]
True... ill fix it
