### ISSUE TITLE
fix: change checkboxes to radio buttons

### ISSUE THREAD

**Issue by MichaHuhn** [zen-browser/www#70]
Currently, the platforms can be selected through checkboxes.

![image](https://github.com/user-attachments/assets/73206625-c781-47f5-bb8c-131bed20991f)
https://www.zen-browser.app/download

When I first visited the page, I thought it was possible to check multiple checkboxes.
In my opinion, it would make more sense to use radio buttons instead. This way it would be more intuitive and accessible because you can also use the arrow keys for the selection.

**Comment by mauro-balades** [comment]
Should be fixed now

**Comment by MichaHuhn** [comment]
@mauro-balades The download options are now divs instead of either buttons or radio buttons. Currently, they can't be selected with the keyboard.
