### ISSUE TITLE
Further problems concerning language and design

### ISSUE THREAD

**Issue by jgh07** [zen-browser/www#77]
Adding on to #46, in my opinion the problems mentioned there are far from the only issues with the site. I am not sure who the target audience is for this browser, but the website gives the impression that it is a hobby project made by one lone developer that struggles with English. In this issue I am listing some things I've noticed that would scare me off from using your product, personally.

General website design:
- The logo constantly changing colors is obnoxious.
- Is that "killer feature" tag really needed for compact mode? Seems like a weird feature to be proud of in particular.
- A minor thing, but adding a heart to the "Donate <3" button seems unprofessional.

Language:
- After the bit about customization it says "Checkout our themes store" where "check out" should be two words. 
- I am not particularly fond of using apostrophes, both for "Firefox's" as well as in "Zen Browser's documentation". For the second example, the apostrophe can just be omitted entirely which reads much better. More examples [here](https://docs.zen-browser.app/themes-store/themes-marketplace-preferences), with the added bonus of not capitalizing Firefox, again.
- The first sentence on [this page](https://docs.zen-browser.app/building-zen-browser/building-zen-browser) should either say "We've taken the time [...]" or "We took the time [...]" instead of "We've took the time [...]".
- The bottom of [this page](https://docs.zen-browser.app/guides/live-editing) contains the following sentence: "This guide is designed to help you quickly and efficiently customize your Zen Browser experience." Something feels off about this sentence, but I honestly can't put my finger on it.
- A relatively minor thing again, but on the first paragraph of [this page](https://docs.zen-browser.app/faq), "our community forums" are mentioned in first person, but in the third paragraph, the "official documentation platforms" are now mentioned in third person. IMO, it would make sense to stick to one person here.

**Comment by NOCanoa** [comment]
yes its done by one dev and English is not his first language thats why PRs are open so anyone can help.

**Comment by mauro-balades** [comment]
All should be fixed except for the Donate <3 thing, im keeping that
