### ISSUE TITLE
Website is inaccessible

### ISSUE THREAD

**Issue by chrislowles** [zen-browser/www#79]
Running Windows 11 23H2 with untouched firewall, can't access Theme Store and main website for downloads, had to download from GitHub directly to check this project out initially.

**Comment by NOCanoa** [comment]
does it display a error or somting?

**Comment by chrislowles** [comment]
This is what turns up, just some general error.

![image](https://github.com/user-attachments/assets/adb884ee-52be-4f42-ad8e-3ca9a8637742)

**Comment by NOCanoa** [comment]
Are u using some weard DNS provider, that is blocking ur dns request?

**Comment by chrislowles** [comment]
I'm currently on my default ISP-provided DNS, turned off extensions to test, went through clearing the cache in the known ways, at least the ones detailed here bar the automatic one https://windowsreport.com/how-to-flush-dns-windows-11/ Still nothing.

**Comment by NOCanoa** [comment]
is ur isp bloking the dns try seting a diferent dns provider example cloudflare/quad9

**Comment by chrislowles** [comment]
Set my DNS to Cloudflare on Max Protection in the DNS over HTTPS section and it's working.

**Comment by tysonclugg** [comment]
Looks like there's an issue with the Vercel account.

> **This Deployment** has been disabled.

> **Your connection** is working correctly.

> **Vercel** is working correctly.

<pre><strong>402</strong>: PAYMENT_REQUIRED<br />Code: `DEPLOYMENT_DISABLED`<br />ID: syd1::qnnxb-1724654733492-f78f7cb96853</pre>

![image](https://github.com/user-attachments/assets/472a0c25-6ac5-4ba0-a923-47b8ddf026a0)

**Comment by tysonclugg** [comment]
Additional context: I've arrived here via recommendation from <https://www.youtube.com/watch?v=tKM2N4TQHQY>, which has 123K views as of the time of this comment.

Is it safe to assume all the new visitors (such as myself) have generated heaps of traffic, and have consumed all [included usage resources](https://vercel.com/docs/limits/overview#included-usage)?

**Comment by shubham0831** [comment]
I'm facing a similar error which isn't letting me access the site. Not sure whether it's the same issue as described above or something else

On Arc
<img width="1430" alt="image" src="https://github.com/user-attachments/assets/100c7b25-2f1e-4992-8bb9-d03cbbb9d4f7">

On firefox
<img width="1430" alt="image" src="https://github.com/user-attachments/assets/e7d01906-095d-43c5-84cd-6f462683cef8">

**Comment by NOCanoa** [comment]
Cheff is fixing versel, upgrading the plan xD

**Comment by spareek831** [comment]
Pretty good problem to have!

**Comment by shubham0831** [comment]
Pretty good problem to have!

**Comment by tysonclugg** [comment]
> Cheff is fixing versel, upgrading the plan xD

Seems to have fixed it, WFM. :smile_cat:
