### ISSUE TITLE
Add href in head for Mastodon verification

### ISSUE THREAD

**Issue by Donnnno** [zen-browser/www#80]
Typescript is a mystery to me, otherwise I would create a PR instead of issue.

Mastodon verification works unlike Twitter by actually verifying the domain name linked to the account. 
So if the following can be added to the head:
`<link rel="me" href="https://fosstodon.org/@zenbrowser">` 
the account will be verified

Bonus:
the account can also be added to the organizations' page here:

![image](https://github.com/user-attachments/assets/6957f387-6dba-4c50-9fb5-5b99c858959f)

**Comment by NOCanoa** [comment]
yeah, the org doent even have a link to the site lol

**Comment by mauro-balades** [comment]
i've just added it

**Comment by Donnnno** [comment]
sick!
