### ISSUE TITLE
The team

### ISSUE THREAD

**Issue by DutchPete** [zen-browser/www#95]
Hi, I downloaded and installed the browser (flatpak version) and have been very pleasantly surprised because it is so much more stable and/or beautiful and/or user friendly than other Firefox forks like Librewolf, Floorp, and others. And it is only an Alpha release. I can tell you that for what I need from a browser, Zen does not at all feel like an Alpha release, it is more like pretty mature Beta release. I am already using it as my daily driver. I am also impressed with the speed of updates  – 3 days ago there were 3 in 1 day !

Nevertheless, I am a bit concerned about the team and your business model. I followed a discussion on [Reddit](https://www.reddit.com/r/browsers/comments/1e1lcs8/zen_browser_first_public_release/), which gave me the impression that "maubg" is the only person working on Zen. If that is the case, is it a fair assumption that started as a hobby for 1 person (@mauro-balades ?) and has been made public? If so, does that mean that when other priorities become more important Zen will have to take a back seat or even become abandonware?

**Comment by mauro-balades** [comment]
It did start as a hobby project but I'm now taking it a bit more seriously

**Comment by DutchPete** [comment]
I am on Discord and looked for the Zen-browser server but it did not find it. Can you send me an invite link?

**Comment by mauro-balades** [comment]
https://discord.gg/nnShMQzR4b
