### ISSUE TITLE
Inconsistent "Go Back" button behavior on theme page

### ISSUE THREAD

**Issue by mwyywm** [zen-browser/www#96]
I noticed that the "Go Back" button on the extension and theme pages at `/themes/[theme]` does not consistently return to the previous page within the theme section. Instead, it navigates back through the browser history. It only goes back to `/themes` if that was the last page visited. 

### Expected behavior:
When clicking the "go back" button it should navigate to https://www.zen-browser.app/themes instead of backwards in the browser history.

**Comment by adityayaduvanshi** [comment]
Its because in the code, we should not use async function component when we are using "use client". 
Please assign this issue to me.
